### ISSUE TITLE
Repo permissions

### ISSUE THREAD

**Issue by afomi** [ContraCostaCivic/Census-In-Field-Canvassing#22]
@silasburger - can you give me access to push branches to this repo? 
or would you prefer a fork & pull-request model?

**Comment by silasbur** [comment]
Hi Ryan, 

I sent you an invite to be a collaborator. Check the email associated with your github account. You should be able to push when you accept.

-Silas

**Comment by afomi** [comment]
got it. thanks @silasburger 

ping me on Slack if you want to pair.
