### ISSUE TITLE
Testing out the app

### ISSUE THREAD

**Issue by afomi** [ContraCostaCivic/Census-In-Field-Canvassing#24]
@silasburger, @klequis, @cycho04, you can check out the app at https://www.canvasser.org. Valid logins for this `TEST` environment are at:

https://github.com/OpenWalnutCreek/canvasser-backend/blob/master/db/seeds.rb

Please leave any questions and feedback in this thread!

**Comment by silasbur** [comment]
Awesome Ryan! I'm definitely interested in continuing to work on this and pairing. I'll take a closer look tomorrow.

-Silas

**Comment by afomi** [comment]
the app is available for testing anytime. Please leave feedback as an Issue in this repo, or let's chat in CfA Slack.
